### ISSUE TITLE
[Feature Request] (or not? idk) allow us to open files within lino

### ISSUE THREAD

**Issue by LollipopFt** [ahmednooor/lino#4]
for example, pepper text editor does this by the command `:open` but i am not sure if you are planning to support this. i do find lino better than pepper for my use case though.

**Comment by ahmednooor** [comment]
@LollipopFt  Thank you for reaching out.

Sorry, multiple files in one instance is not in the plan right now. If you liked lino due to notepad like keybindings, you can check out [micro](https://github.com/zyedidia/micro). It has multiple files feature. Thanks.
